// AUTO-GENERATED by app/lib/customSync.js — do not edit by hand.
// Project-owned chrome overlay, exposed as a runtime OBJECT so lib/chromeReg.js
// can read a name that may be absent without a static "export not found" break.

function isComp(v) {
  if (typeof v === 'function') return true;
  return !!(v && typeof v === 'object' && v.$$typeof);
}
function pick(mod, name) {
  if (!mod) return null;
  if (isComp(mod.default)) return mod.default;
  if (isComp(mod[name])) return mod[name];
  for (const k of Object.keys(mod)) if (isComp(mod[k])) return mod[k];
  return null;
}

export const CHROME = Object.fromEntries(Object.entries({
}).filter(([, v]) => v));
