// AUTO-GENERATED by app/lib/customSync.js — do not edit by hand.
// Project-owned chrome overlay, exposed as a runtime OBJECT so lib/chromeReg.js
// can read a name that may be absent without a static "export not found" break.
import * as m_AuthModal from './AuthModal.jsx';
import * as m_BillLines from './BillLines.jsx';
import * as m_CartSheet from './CartSheet.jsx';
import * as m_Catalogue from './Catalogue.jsx';
import * as m_CheckoutPanel from './CheckoutPanel.jsx';
import * as m_EntrySequence from './EntrySequence.jsx';
import * as m_Header from './Header.jsx';
import * as m_Hero3DSection from './Hero3DSection.jsx';
import * as m_HeroScene from './HeroScene.jsx';
import * as m_OrderReceipt from './OrderReceipt.jsx';
import * as m_StoreCard from './StoreCard.jsx';
import * as m_StoreHeader from './StoreHeader.jsx';

function isComp(v) {
  if (typeof v === 'function') return true;
  return !!(v && typeof v === 'object' && v.$$typeof);
}
function pick(mod, name) {
  if (!mod) return null;
  if (isComp(mod.default)) return mod.default;
  if (isComp(mod[name])) return mod[name];
  for (const k of Object.keys(mod)) if (isComp(mod[k])) return mod[k];
  return null;
}

export const CHROME = Object.fromEntries(Object.entries({
  AuthModal: pick(m_AuthModal, 'AuthModal'),
  BillLines: pick(m_BillLines, 'BillLines'),
  CartSheet: pick(m_CartSheet, 'CartSheet'),
  Catalogue: pick(m_Catalogue, 'Catalogue'),
  CheckoutPanel: pick(m_CheckoutPanel, 'CheckoutPanel'),
  EntrySequence: pick(m_EntrySequence, 'EntrySequence'),
  Header: pick(m_Header, 'Header'),
  Hero3DSection: pick(m_Hero3DSection, 'Hero3DSection'),
  HeroScene: pick(m_HeroScene, 'HeroScene'),
  OrderReceipt: pick(m_OrderReceipt, 'OrderReceipt'),
  StoreCard: pick(m_StoreCard, 'StoreCard'),
  StoreHeader: pick(m_StoreHeader, 'StoreHeader'),
}).filter(([, v]) => v));
