// AUTO-GENERATED by app/lib/customSync.js — do not edit by hand.
// Static imports on purpose: a dynamic import context broke hydration.
//
// NAMESPACE imports, not default imports. This was a real bug: the AI wrote
// ReviewMarquee.jsx with `export function ReviewMarquee()` and no default
// export, so `import ReviewMarquee from ...` resolved to undefined. The key was
// present in CUSTOM but its value was not a component, so the section rendered
// "Preparing…" forever while a sibling component with `export default` rendered
// fine — the asymmetry that gave it away. We cannot dictate the export style of
// code a model writes on request, so accept every valid one instead.
import * as m_BellHero from './BellHero.jsx';
import * as m_ClassCheckout from './ClassCheckout.jsx';
import * as m_ClassDetail from './ClassDetail.jsx';
import * as m_ClassSearch from './ClassSearch.jsx';
import * as m_CreateAccount from './CreateAccount.jsx';
import * as m_DatePicker from './DatePicker.jsx';
import * as m_EnrollConfirm from './EnrollConfirm.jsx';
import * as m_EnrollHeader from './EnrollHeader.jsx';
import * as m_HippoChatLauncher from './HippoChatLauncher.jsx';
import * as m_HowLiveWorks from './HowLiveWorks.jsx';
import * as m_LiveCatalogue from './LiveCatalogue.jsx';
import * as m_LiveClasses from './LiveClasses.jsx';
import * as m_MeetTheInstructor from './MeetTheInstructor.jsx';
import * as m_MySubscriptions from './MySubscriptions.jsx';
import * as m_Profile from './Profile.jsx';
import * as m_ProfileLink from './ProfileLink.jsx';
import * as m_RecurringSummary from './RecurringSummary.jsx';
import * as m_SearchHero from './SearchHero.jsx';
import * as m_StartingThisWeek from './StartingThisWeek.jsx';
import * as m_SubjectTiles from './SubjectTiles.jsx';
import * as m_SubscribeScheduler from './SubscribeScheduler.jsx';
import * as m_SubscriptionConfirm from './SubscriptionConfirm.jsx';
import * as m_TeacherApproach from './TeacherApproach.jsx';
import * as m_TeacherDirectory from './TeacherDirectory.jsx';
import * as m_TeacherEditorial from './TeacherEditorial.jsx';
import * as m_TeacherFAQ from './TeacherFAQ.jsx';
import * as m_TeacherTrust from './TeacherTrust.jsx';
import * as m_TrustStrip from './TrustStrip.jsx';
import * as m_UpcomingClasses from './UpcomingClasses.jsx';
import * as m_WhatParentsSay from './WhatParentsSay.jsx';

function isComp(v) {
  if (typeof v === 'function') return true;              // function or class component
  return !!(v && typeof v === 'object' && v.$$typeof);   // memo() / forwardRef()
}

// default → export matching the filename → the first component-shaped export.
function pick(mod, name) {
  if (!mod) return null;
  if (isComp(mod.default)) return mod.default;
  if (isComp(mod[name])) return mod[name];
  for (const k of Object.keys(mod)) if (isComp(mod[k])) return mod[k];
  return null;
}

// Unresolvable entries are DROPPED, not stored as null: Object.keys(CUSTOM) is
// what the UI shows as "Ready now", and it must not promise a broken section.
export const CUSTOM = Object.fromEntries(Object.entries({
  BellHero: pick(m_BellHero, 'BellHero'),
  ClassCheckout: pick(m_ClassCheckout, 'ClassCheckout'),
  ClassDetail: pick(m_ClassDetail, 'ClassDetail'),
  ClassSearch: pick(m_ClassSearch, 'ClassSearch'),
  CreateAccount: pick(m_CreateAccount, 'CreateAccount'),
  DatePicker: pick(m_DatePicker, 'DatePicker'),
  EnrollConfirm: pick(m_EnrollConfirm, 'EnrollConfirm'),
  EnrollHeader: pick(m_EnrollHeader, 'EnrollHeader'),
  HippoChatLauncher: pick(m_HippoChatLauncher, 'HippoChatLauncher'),
  HowLiveWorks: pick(m_HowLiveWorks, 'HowLiveWorks'),
  LiveCatalogue: pick(m_LiveCatalogue, 'LiveCatalogue'),
  LiveClasses: pick(m_LiveClasses, 'LiveClasses'),
  MeetTheInstructor: pick(m_MeetTheInstructor, 'MeetTheInstructor'),
  MySubscriptions: pick(m_MySubscriptions, 'MySubscriptions'),
  Profile: pick(m_Profile, 'Profile'),
  ProfileLink: pick(m_ProfileLink, 'ProfileLink'),
  RecurringSummary: pick(m_RecurringSummary, 'RecurringSummary'),
  SearchHero: pick(m_SearchHero, 'SearchHero'),
  StartingThisWeek: pick(m_StartingThisWeek, 'StartingThisWeek'),
  SubjectTiles: pick(m_SubjectTiles, 'SubjectTiles'),
  SubscribeScheduler: pick(m_SubscribeScheduler, 'SubscribeScheduler'),
  SubscriptionConfirm: pick(m_SubscriptionConfirm, 'SubscriptionConfirm'),
  TeacherApproach: pick(m_TeacherApproach, 'TeacherApproach'),
  TeacherDirectory: pick(m_TeacherDirectory, 'TeacherDirectory'),
  TeacherEditorial: pick(m_TeacherEditorial, 'TeacherEditorial'),
  TeacherFAQ: pick(m_TeacherFAQ, 'TeacherFAQ'),
  TeacherTrust: pick(m_TeacherTrust, 'TeacherTrust'),
  TrustStrip: pick(m_TrustStrip, 'TrustStrip'),
  UpcomingClasses: pick(m_UpcomingClasses, 'UpcomingClasses'),
  WhatParentsSay: pick(m_WhatParentsSay, 'WhatParentsSay'),
}).filter(([, v]) => v));
